# Tell the scanner to explicitly look into both your code folders
sonar.sources=frontend,backend

# The rest of your properties remain the same
sonar.projectKey=openshift-helm-infra-project
sonar.projectName=Openshift Helm Infrastructure Project
sonar.host.url=http://34.134.253.20:9000
