project_id    = "your-gcp-project-id"
region        = "us-central1"
zone          = "us-central1-a"
network_name  = "library-vpc"
subnet_cidr   = "10.0.1.0/24"
instance_name = "library-app-instance"
machine_type  = "e2-medium"
