apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-app
          image: rukevweubio/backend-book-app:fe7bcb980424cb683680e170e105375ae0738d50
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://database-service:3306/librarydb?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
