name: Build gitaction workflow that deploy docker image to kubernestes  and google cloud 

on:
  push:
    branches:
       - qa 
    paths:
      - frontend/*
      - backend/*
      - .github/workflows/qa.ci.yaml 

permissions:
   contents: write 
   id-token: write 

jobs:
  gitleak-scan:
    name: Gitleak Scan 
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Gitleak scan 
        run: |
          docker run --rm \
              -v "${{ github.workspace }}:/repo" \
              zricethezav/gitleaks:latest detect \
              --source=/repo \
              --report-format=json \
              --report-path=/repo/gitleaks-report.json \
              --redact \
              --exit-code 0
      - name: Upload Artifact 
        uses: actions/upload-artifact@v4 
        with: 
           name:  gitleak-report
           path: ${{ github.workspace }}/gitleaks-report.json
           if-no-files-found: warn 
